# config.yml
recipe: default.v1
language: en

assistant_id: voice_banking_assistant

pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      model_group: nebius_llm
    flow_retrieval:
      embeddings:
        model_group: nebius_embeddings

policies:
  - name: FlowPolicy